[package]
name = "ckb-vm-definitions"
description = "Common definition files for CKB VM"
version = "0.19.1"
license = "MIT"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2018"
autobins = false

[features]
chaos_mode = []

[[bin]]
name = "generate_asm_constants"
path = "src/generate_asm_constants.rs"
